name: CI/CD to Azure

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 
    
    - name: Install dependencies
      run: npm install
    
    - name: Deploy to Azure
      run: |
        ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} \
          ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
          "cd /home/kingmonte/Dev && \
          rm -rf * && \
          mkdir -p ./liverpoolapp && \
          mv -f ./dist/* ./liverpoolapp && \
          npm restart"
